Added trivyignore

diff --git a/.github/workflows/build_publish.yml b/.github/workflows/build_publish.yml
--- a/.github/workflows/build_publish.yml
+++ b/.github/workflows/build_publish.yml
@@ -10,6 +10,7 @@ on:
 
 jobs:
   Trivy:
+    name: 🕵️‍♂️ Trivy Scan
     runs-on: ubuntu-latest
     steps:
       - name: 📥 Checkout code
@@ -38,11 +39,11 @@ jobs:
         uses: docker/setup-qemu-action@v2
       - name: 🖥️ Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
-      # - name: 🔐 Login to DockerHub
-      #   uses: docker/login-action@v2
-      #   with:
-      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
-      #     password: ${{ secrets.DOCKER_HUB_TOKEN }}
+      - name: 🔐 Login to DockerHub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKER_HUB_USERNAME }}
+          password: ${{ secrets.DOCKER_HUB_TOKEN }}
       - name: 🐳 Docker Build and push
         uses: docker/build-push-action@v3
         with:
@@ -54,22 +55,22 @@ jobs:
             bahmni/ipd-frontend:ipd-${{ github.run_number }}
             bahmni/ipd-frontend:ipd
 
-  # trigger-workflow:
-  #   name: 🔁 Trigger workflow to deploy to Docker env
-  #   needs:
-  #     - build-publish-docker
-  #     - Trivy
-  #   runs-on: ubuntu-latest
-  #   env:
-  #     EVENT_TYPE: bahmni-ipd-frontend
-  #   steps:
-  #     - name: 🔧 Create repository_dispatch
-  #       run: |
-  #         trigger_result=$(curl -s -o trigger_response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.IPD_PAT }}' https://api.github.com/repos/${{ secrets.IPD_ORG_NAME }}/${{ secrets.IPD_REPOSITORY_NAME }}/dispatches -d '{"event_type":"'"${EVENT_TYPE}"'"}')
-  #         if [ $trigger_result == 204 ];then
-  #           echo "✅ Trigger to $ORG_NAME/$REPOSITORY_NAME Success"
-  #         else
-  #           echo "❌ Trigger to $ORG_NAME/$REPOSITORY_NAME Failed"
-  #           cat trigger_response.txt
-  #           exit 1
-  #         fi
+  trigger-workflow:
+    name: 🔁 Trigger workflow to deploy to Docker env
+    needs:
+      - build-publish-docker
+      - Trivy
+    runs-on: ubuntu-latest
+    env:
+      EVENT_TYPE: bahmni-ipd-frontend
+    steps:
+      - name: 🔧 Create repository_dispatch
+        run: |
+          trigger_result=$(curl -s -o trigger_response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.IPD_PAT }}' https://api.github.com/repos/${{ secrets.IPD_ORG_NAME }}/${{ secrets.IPD_REPOSITORY_NAME }}/dispatches -d '{"event_type":"'"${EVENT_TYPE}"'"}')
+          if [ $trigger_result == 204 ];then
+            echo "✅ Trigger to $ORG_NAME/$REPOSITORY_NAME Success"
+          else
+            echo "❌ Trigger to $ORG_NAME/$REPOSITORY_NAME Failed"
+            cat trigger_response.txt
+            exit 1
+          fi
